import type { Doctor } from "@/lib/doctor-locator";
import maleDoctorOne from "../../doctors/drs/men/ChatGPT Image Jun 29, 2026, 03_07_35 PM.png";
import maleDoctorTwo from "../../doctors/drs/men/ChatGPT Image Jun 29, 2026, 03_07_40 PM (1).png";
import femaleDoctorOne from "../../doctors/drs/women/ChatGPT Image Jun 29, 2026, 03_07_40 PM (2).png";
import femaleDoctorTwo from "../../doctors/drs/women/ChatGPT Image Jun 29, 2026, 03_07_41 PM (3).png";
import femaleDoctorThree from "../../doctors/drs/women/ChatGPT Image Jun 29, 2026, 03_07_41 PM (4).png";
import femaleDoctorFour from "../../doctors/drs/women/ChatGPT Image Jun 29, 2026, 03_07_42 PM (5).png";

export const fakeDoctors: Doctor[] = [
  {
    id: 1,
    name: "Dr. Omar Hassan",
    specialty: "دكتور قلب",
    rating: 4.9,
    price: 650,
    latitude: 30.0439,
    longitude: 31.2357,
    address: "12 Nile Corniche, Garden City, Cairo",
    area: "Garden City",
    phone: "+20 100 123 4567",
    image: maleDoctorOne,
    availableToday: true,
    experienceYears: 14,
    searchAliases: ["cardiologist", "heart doctor", "قلب"],
  },
  {
    id: 2,
    name: "Dr. Sara Khaled",
    specialty: "Therapist",
    rating: 4.8,
    price: 500,
    latitude: 30.0488,
    longitude: 31.2389,
    address: "45 Tahrir Street, Downtown, Cairo",
    area: "Downtown",
    phone: "+20 100 222 3344",
    image: femaleDoctorOne,
    availableToday: true,
    experienceYears: 10,
    searchAliases: ["therapy", "psychologist", "معالج", "علاج نفسي"],
  },
  {
    id: 3,
    name: "Dr. Ahmed Mostafa",
    specialty: "طوارئ",
    rating: 4.6,
    price: 350,
    latitude: 30.0928,
    longitude: 31.3235,
    address: "8 El-Thawra Avenue, Heliopolis, Cairo",
    area: "Heliopolis",
    phone: "+20 100 555 6677",
    image: maleDoctorTwo,
    availableToday: false,
    experienceYears: 8,
    searchAliases: ["emergency", "emergency doctor", "طواريء", "اسعاف"],
  },
  {
    id: 4,
    name: "Dr. Mona Youssef",
    specialty: "تحاليل",
    rating: 4.85,
    price: 450,
    latitude: 30.0589,
    longitude: 31.2201,
    address: "3 Corniche El-Nil, Zamalek, Cairo",
    area: "Zamalek",
    phone: "+20 100 777 8899",
    image: femaleDoctorTwo,
    availableToday: true,
    experienceYears: 12,
    searchAliases: ["lab", "lab doctor", "laboratory", "معمل", "تحاليل طبية"],
  },
  {
    id: 5,
    name: "Dr. Laila Nasser",
    specialty: "Therapist",
    rating: 4.75,
    price: 400,
    latitude: 30.0617,
    longitude: 31.2001,
    address: "21 Syria Street, Mohandessin, Giza",
    area: "Mohandessin",
    phone: "+20 101 333 9090",
    image: femaleDoctorThree,
    availableToday: true,
    experienceYears: 9,
    searchAliases: ["therapy", "psychologist", "معالج", "علاج نفسي"],
  },
  {
    id: 6,
    name: "Dr. Youssef Adel",
    specialty: "تحاليل",
    rating: 4.55,
    price: 280,
    latitude: 30.0169,
    longitude: 31.4147,
    address: "90 Road 9, New Cairo, Cairo",
    area: "New Cairo",
    phone: "+20 111 450 8890",
    image: maleDoctorOne,
    availableToday: true,
    experienceYears: 7,
    searchAliases: ["lab", "lab doctor", "laboratory", "معمل", "تحاليل طبية"],
  },
  {
    id: 7,
    name: "Dr. Mariam Fouad",
    specialty: "دكتور قلب",
    rating: 4.95,
    price: 800,
    latitude: 30.0252,
    longitude: 31.2109,
    address: "17 El-Malek El-Saleh Street, Manial, Cairo",
    area: "Manial",
    phone: "+20 120 678 4455",
    image: femaleDoctorFour,
    availableToday: false,
    experienceYears: 18,
    searchAliases: ["cardiologist", "heart doctor", "قلب"],
  },
  {
    id: 8,
    name: "Dr. Karim Samir",
    specialty: "طوارئ",
    rating: 4.7,
    price: 300,
    latitude: 29.9642,
    longitude: 31.2657,
    address: "5 Street 206, Maadi, Cairo",
    area: "Maadi",
    phone: "+20 102 345 7788",
    image: maleDoctorTwo,
    availableToday: true,
    experienceYears: 11,
    searchAliases: ["emergency", "emergency doctor", "طواريء", "اسعاف"],
  },
];

// Swap this function with a real backend call when the doctors API is ready.
export async function fetchFakeDoctors() {
  return Promise.resolve(fakeDoctors);
}
